### ISSUE TITLE
How to handle UDP connections

### ISSUE THREAD

**Issue by saaam000** [tabjy/android-vpn-tun2socks#4]
How to handle UDP connections ? currently it's just handling TCP connections.

**Comment by tabjy** [comment]
iirc, UDP is supported if the SOCKS5 server supports the UDP Bind command.  See [here](https://github.com/tabjy/android-vpn-tun2socks/blob/e5e4f1900f9397fdbcb4968213c4dbe8e146cb42/app/src/main/java/com/example/test/MyVpnService.java#LL38C80-L38C88).

The Android VPN service works on the IP layer, so it doesn't really distinguish TCP or UDP. Should you continue to experience this problem, try tun2socks with your server directly and report to the upstream if the problem persists.
