### ISSUE TITLE
Can I use tun2socks to handle all DNS query

### ISSUE THREAD

**Issue by vicweiyu** [tabjy/android-vpn-tun2socks#6]
Hello,

Sorry to bother you. I'm a freshman in Android and network programming. I want to build an application to handle all DNS queries for my application and use a custom DNS provider (like cloudfare, google). May I know it can be achieved with tun2socks without remote server.

Thank you.

Victor

**Comment by tabjy** [comment]
Sorry for the slow turnaround.

Yes, if you could build a local SOCKS5 server (in what-ever-language) that directly dials without a remote proxy. Intercept all DNS DUP packets, resolve and reply.

However, this sounds like a XY problem. Are you aware of the private DNS [0] feature on Android?

[0] https://developers.cloudflare.com/1.1.1.1/setup/android/
